### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShadowGaming100** [NOVA-Discord-Bot/NOVA#1]
Error: The class/prototype returned from the extender function must extend the existing structure class/prototype (received function ExtendedTextChannel extends TextChannel; expected extension of ExtendedTextChannel).
    at Function.extend (/home/runner/Dark-Cloder-Global/node_modules/discord.js/src/util/Structures.js:82:13)
    at module.exports (/home/runner/Dark-Cloder-Global/node_modules/discord-buttons/src/index.js:24:16)
    at Object.<anonymous> (/home/runner/Dark-Cloder-Global/index.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Dark-Cloder-Global/events/chatbot.js:1:16)H

**Comment by ShadowGaming100** [comment]
> Error: The class/prototype returned from the extender function must extend the existing structure class/prototype (received function ExtendedTextChannel extends TextChannel; expected extension of ExtendedTextChannel).
> at Function.extend (/home/runner/Dark-Cloder-Global/node_modules/discord.js/src/util/Structures.js:82:13)
> at module.exports (/home/runner/Dark-Cloder-Global/node_modules/discord-buttons/src/index.js:24:16)
> at Object. (/home/runner/Dark-Cloder-Global/index.js:9:1)
> at Module._compile (internal/modules/cjs/loader.js:999:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> at Module.load (internal/modules/cjs/loader.js:863:32)
> at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> at Module.require (internal/modules/cjs/loader.js:887:19)
> at require (internal/modules/cjs/helpers.js:74:18)
> at Object. (/home/runner/Dark-Cloder-Global/events/chatbot.js:1:16)


dint have the updated  code
